apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: subscription-service
          image: subscription-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            # --- Database ---
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://subscription-db:5432/subscription_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"

            # --- JPA ---
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # --- Kafka ---
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
