apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-db
  template:
    metadata:
      labels:
        app: ticket-db
    spec:
      containers:
        - name: ticket-db
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: ticket_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: ticket-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: ticket-db-storage
          persistentVolumeClaim:
            claimName: ticket-db-pvc
