apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: payment_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: payment-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: payment-db-storage
          persistentVolumeClaim:
            claimName: payment-db-pvc
