apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: ticket-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            # --- Database ---
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://ticket-db:5432/ticket_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"

            # --- JPA ---
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

            # --- Kafka ---
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"

            # --- Payment service URL ---
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:8085/api/payments/process"
