apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-db
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: notification_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: notification-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: notification-db-storage
          persistentVolumeClaim:
            claimName: notification-db-pvc
